DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS phases;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS users;

DROP SEQUENCE IF EXISTS users_id_seq;
DROP SEQUENCE IF EXISTS teams_id_seq;
DROP SEQUENCE IF EXISTS projects_id_seq;
DROP SEQUENCE IF EXISTS phases_id_seq;
DROP SEQUENCE IF EXISTS tasks_id_seq;
